language: ruby
rvm:
- 2.2
#- 2.1
#- 2.0
- 1.9.3

env:
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.5.1

services:
  - docker

script:
  - wget -qO- bit.ly/ansibletest | sh

after_failure:
  - cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
      - secure: e9loqnN9M+6REmPTKQx4AUNOTHcSvZQNh0uC36vZqJjD8l01HUEOHishZQJ9ctBxityRnzX7s8kEkhN3EBmDc0dqOU3VC82mNgi/Aps9BXP4XLp3qJg85hStuVF4HedFeheqJD4XWLhjSqPkRBRROgtZ9OFt9xupSiMfWDJ9cCnCYnK3PKxQ4hs52LTk3/tsHcthZEO7Yzxm5zGB0ymvmbMUzcar0me8C73BDZTVPLTeFlY1vtmYJzikWC9Sbc+XsMyiYAhF9dwmJdjNWiUGO8jLyOPoJBGFv3vsvsSM/TAVk6/ojtkcd3Nq64AcXXmePIXJWizNtZvRdJgFjAl3PYoDNBcg/YDJgGiFYkpYFZrX69O2/aGGruV/S25KnbcavWgqe9h93j0Hrvuc9HOErpjcwTLO4lmOnECk9Tz79+m78HNA7vxXs1QFUqh/u0sculkd6982Wjix1Hs7rezd6HWQoxAnRHDjdxEXVgcZga+1me3wjcVXPsNRbN/SmwPqgMLd8scPWzmE30eTtKji8mfe4HGk9lQsBOGYreTvKXAfjyBatp8C88Qcn5aElSgbTqCbaJd26xKgJohvD3yX+/iLFOPHiGnG/jqHE92HGPpQANkXMJ03UuVLgk2Ty7P2zApb+54M4pd5XzBhRJ+/JM5hCcMCjGsaCXDROJfIBSU=
  email:
    recipients:
      secure: p/8OTJP15Xi0RSiQxeDgYBP9V116EHQ8YEYzVeqClJbMPPLnqO43s8p1uqqTXSVWf69EEyv7/UAavejZonEPg2APma1wuYc20Vsh1v0x02xtAHkiDq7QbycAfNknTimuwuTZnSOMAAqzCfZzBBtr63q6AOsQ8V3gRw6IBjMOjxyYQmpqBsZ8tKqWdJGEp7gfJEpCwLmnZe7HX8yUeBWlofLMg4ldaYdlJ/pRaaYvVoCNkss8Rxmvv2tnKmktm2my+cCCpFlGSU6QLgc7YTZ/gdpttnv1UIbbBc93nXLJ8PVzzIYDi6dDfVjk/JvOD6YClhUUyRQ7io6V7DzPw486ciscHx7BIMxEPcj0ZsiJj6BI0cK4lWFcoEp+DmBL604NakEXpcXlHab6xufB4LSMnACc3zP+uMGG3khqvsIfnyc5gjPOVSMUbhyfIrnNnzsa/d59Ox4kIUsKpDKB0/IpntHfWLrh9V7Qoo7Eb1nUX2FUWAwO90MIoN1Bbq30YlaTcEN2n+DYoYAqjB7VhB16AIiQLpG5Pnl6KloCus4oY/B/ViX2UzBrR8z+20mBFo2E0X1Vi9P/uAKyAK607roGjczkgUxMgyC3Nqunmsq+o5otYtS5zjOSceYPiD2PNMlwK3sT0YFT99wPJiLtAioog0bov5iVpxn2jsnVCsEbE2w=
