---
- include: compat.yml

- include: include_vars.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: install_package_names.yml

- name: Configure /net
  sudo: yes
  lineinfile: "state={{autofs_net_state}}
    dest=/etc/auto.master
    line='/net\t-hosts'
    regexp='/net.*-hosts'"
