---
- name: check for short-circuit
  raw: "> /dev/null test -d /usr/share/doc/autofs;"
  register: installed
  ignore_errors: True
  changed_when: False

- name: set should_run fact
  set_fact:
    should_run: "{{installed|failed or not autofs_should_shortcircuit}}"

- include: include_vars.yml
- include: sudoorbecome.yml
