---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: install autofs with ansible module
  action: "{{backcompat_pkg_mgr}} name=autofs"
  sudo: yes
  when: backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt"

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install autofs with dnf
  command: dnf install -y autofs
  args:
    creates: /etc/auto.master
  sudo: yes
  when: backcompat_pkg_mgr == "dnf"

- name: Configure /net
  sudo: yes
  lineinfile: "state={{autofs_net_state}}
    dest=/etc/auto.master
    line='/net\t-hosts'
    regexp='/net.*-hosts'"
